# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_auto_20160301_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={},
        ),
        migrations.RemoveField(
            model_name='click',
            name='bookmark_url',
        ),
        migrations.RemoveField(
            model_name='click',
            name='time_created',
        ),
        migrations.AddField(
            model_name='click',
            name='clicked',
            field=models.BooleanField(default=True),
        ),
    ]
