# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_auto_20160302_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='url',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='url_app.Bookmark'),
            preserve_default=False,
        ),
    ]
