# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0005_bookmark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
